name: Android CI
on: 
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: '17'
      - name: Make gradlew executable and change permissions
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      # Only run lint if the branch is not main branch
      - name: Run Lint
        run: |
            if [ "$GITHUB_REF" != "refs/heads/main" ]; then
              ./gradlew lint
            else
              echo "Skipped lint because the branch is main."
            fi
      - name: Upload APK
        uses: actions/upload-artifact@v3.1.3
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
